### ISSUE TITLE
firmata.js should be a standalone library like jquery

### ISSUE THREAD

**Issue by nisen** [firmata/firmata.js#129]
## a standalone lib

1. it can used in Browser at Clinet
2. it can used in Nodejs at Server

**Comment by nisen** [comment]
## How to Do?

 1. change libs/com.js 
 2. remove require("browser-serialport");  and  require("serialport");
 3. add  es6-shim  to libs dir
 4. copy libs/*.js to firmata.js

## RoadMap

    a Pure JavaScript Implementation. A Standalone Lib

**Comment by nisen** [comment]
https://github.com/osokay/firmata.js

**Comment by soundanalogous** [comment]
firmata.js already is a standalone library and a pure JavaScript implementation.
