### ISSUE TITLE
is serialConfig required before using serialWrite/Read/etc?

### ISSUE THREAD

**Issue by jywarren** [firmata/firmata.js#141]
I'd like to submit a PR to clarify this if so: https://github.com/firmata/firmata.js#serial

Also, I can add a clarification if the `board.serialConfig(options)` "options" parameter should have property names like:

```js
{
  portId: <value>,
  baud: <value>
}
```

I think it's a little ambiguous as it's shown currently, and it'd be preferable to have true parse-able JSON shown in the README.

Thanks a lot! Love this library!

**Comment by soundanalogous** [comment]
Yes in Firmata you must always first send a config command for almost every type of communication.

**Comment by soundanalogous** [comment]
`portId` is required, `baud` is optional (defaults to 57600).

In hindsight, the signature of serialConfig should have probably been:
`Board.prototype.serialConfig = function(portId, options)`

**Comment by jywarren** [comment]
Well, next major release, perhaps. OK - opened a PR!
