### ISSUE TITLE
Advanced firmata to drive steppers over wifi

### ISSUE THREAD

**Issue by gokhandilek** [firmata/firmata.js#164]
Hi, I was wondering if I can use the standardfirmatawifi to drive steppers?
By looking at the source code of the standardfirmatawifi, I could not see anything regarding steppers. Can I add the steppers code form the advanced firmata library?

**Comment by soundanalogous** [comment]
You cannot since StandardFirmataWiFi does not (and will not) include stepper motor support. You need to use ConfigurableFirmata or firmatabuilder.com to configure a sketch that supports both WiFi and stepper motors.

**Comment by gokhandilek** [comment]
Firmatabuilder solved my issue. Thank you.
