### ISSUE TITLE
Adding DHT11 or DHT22 sensor support

### ISSUE THREAD

**Issue by piotrfalba** [firmata/firmata.js#19]
It would be great to have DHT11 or DHT22 humidity, temperature sensor support.

**Comment by kenchris** [comment]
It is actually not that bad :-)

https://github.com/01org/webbluetooth-edison-demo/blob/master/zephyr/sensor_core/src/main.c#L119-L227

And most of the treatment of the data is not timing sensitive and can easily be done in JavaScript

**Comment by soundanalogous** [comment]
The way to do this going forward will likely be to use the new DeviceFirmata feature once that gets merged into ConfigurableFirmata: https://github.com/firmata/ConfigurableFirmata/pull/52

**Comment by arthurlutz** [comment]
I would have like use DHT11 or DHT22 from johnny-five but it seems that this is not a use case for it, or for firmata, am I missing something ? Trying to figure out if a more "low level" approach such as https://www.espruino.com/DHT11 can be used in conjunction with firmata and js...

**Comment by reimertz** [comment]
Hi there, I just want to flag that this feature is added in the Configurable Firmware: https://github.com/firmata/protocol/blob/master/dhtsensor.md.

But it seems the appropriate `DHTSENSOR_DATA = 0x74`  hasn't been added to this project. 

Would the addition of this constant +  appropriate response handling enable for us to interact with the DHT sensors?
