### ISSUE TITLE
Analog Pins constant Voltage

### ISSUE THREAD

**Issue by djc-arduino** [firmata/firmata.js#243]
Hey,
im using a Arduino Mega with the Standart Firmata script. When the Arduino is connetcet with the PC The anlog pins
are on constant Voltage. WHY

**Comment by jguille2** [comment]
Hi,
If I understand your question, I think the answer is that in Firmata, all pins are initially in OUTPUT mode, in LOW state.

Maybe this is not the best from an electronic point of view (you can find different issues and discussions about this, and requests to change this for future versions). But now, this is the current behavior.

Joan
