### ISSUE TITLE
Firmata OVER I2C

### ISSUE THREAD

**Issue by beriberikix** [firmata/firmata.js#33]
Has anyone figured out how to communicate over I2C? Not control an I2C pin on an arduino but use I2C to control a board. 

Use case: Raspberry has an I2C and I want to control multiple boards over I2C. There's only so many USB hubs in the world, after all.

On a related note, any clue what the I2Cfirmata does differently than the StandardFirmata? Could it help here?

https://github.com/arduino/Arduino/blob/master/libraries/Firmata/examples/I2CFirmata/I2CFirmata.ino

**Comment by jaretburkett** [comment]
Has anyone made progress on this? I searched for it, but didn't find anything. I was about to start working on it myself, if no one else has gotten it.

**Comment by beriberikix** [comment]
not me. /cc @rwaldron

**Comment by soundanalogous** [comment]
Support would first need to be added to [Firmata](https://github.com/firmata/arduino). Firmata supports uses Stream as the communication interface so it would be compatible with I2C. However I suspect it may not be that straight forward.

**Comment by nimish** [comment]
Any progress on this? Replacing Serial with Wire isn't possible directly due to the different protocol semantics between I2C and UART: the bus master has to initiate each communication.

**Comment by soundanalogous** [comment]
I have no plan to do this myself, but am open to contributions.

**Comment by jaretburkett** [comment]
I did made something that works, but it is not based on firmata, just a similar concept. There were so many hurdles to go through to get it working with firmata. Really, if your like me, you want i2c so you can basically make a port expander for another microcontroller. Here is what I came up with. https://github.com/jaretburkett/Arduino-I2C-Port-Expander .

**Comment by nimish** [comment]
@jaretburkett I'm look at more of a RPi->arduino control, where the realtime stuff is handled mostly on the arduino. My use-case is the grovepi, which has a atmega328p on the I2C bus using a similar protocol to yours, accepting slave inputs from the master RPi.

Firmata just has a greater ecosystem, so i'd like to take the lazy way and reuse as much of it as possible

**Comment by woutervddn** [comment]
Also looking for this. Like the fact that @jaretburkett has a solution that actually works as converting firmata to use i2c seems to Involved to do without in depth knowledge

**Comment by alfredosola** [comment]
I came here to add support for this feature, although sadly it is above my ability to actually implement it.

I think this would make the best use of hardware resources, since the Raspberry would be able to monitor the serial port of the Arduino continuously as well as use it to update the firmware, while actual I/O takes place on a separate channel that doesn't require additional USB to serial hardware.
