### ISSUE TITLE
Custom Arduino code support

### ISSUE THREAD

**Issue by denisidoro** [firmata/firmata.js#78]
I want to control some Dynamixel AX12 servos, which use the SerialPort. I use a custom Arduino library for that, so there are custom functions in the file StandandFirmata, uploaded to my Arduino. 
How can I call them from Node?
I have already tried writing `Firmata.attach(0x01, myCallback);` in Arduino and adding a custom case in the JS files but that didn't work.

**Comment by techniq** [comment]
@rwaldron / @jgautier  - Are there any examples of adding your own SYSEX commands and handling them in Node?  I found an [instructable](http://www.instructables.com/id/Going-Beyond-StandardFirmata-Adding-New-Device-Sup/?ALLSTEPS) on how to do this with PyMata (that I've only glanced so far, but plan to read soon) but I want to use Node.

I currently have an Arduino sketch using [rc-switch](https://github.com/sui77/rc-switch) that I want to expose to Node/firmata.  It needs microsecond timing for the radio codes so I need to do the processing on the Arduino and relay the results down (as well as pass the codes up that I want to transmit)
